## Section 1: Combining and Cleaning Data

### `pd.concat()`
- **Purpose**: Combines multiple DataFrames into one.

- **Key Parameter**:
    - `ignore_index`: When set to `True` resets the index so that the resulting DataFrame has a new continuous index.

In [4]:
import pandas as pd

# Department 1 data
df_dept1 = pd.DataFrame({
    'EmployeeID': [101, 102, 103],
    'Name': ['Alice', 'Bob', 'Michael'],
    'Department': ['Sales', 'Sales', 'Sales'],
    'Salary': [60000, 62000, 61000]
})

# Department 2 data
df_dept2 = pd.DataFrame({
    'EmployeeID': [104, 105],
    'Name': ['David', 'Henry'],
    'Department': ['Marketing', 'Marketing'],
    'Salary': [65000, 67000]
})

# Concatenating the two DataFrames (vertical concatenation)
df_employees = pd.concat([df_dept1,df_dept2],ignore_index=True)
df_employees

   EmployeeID     Name Department  Salary
0         101    Alice      Sales   60000
1         102      Bob      Sales   62000
2         103  Michael      Sales   61000
3         104    David  Marketing   65000
4         105    Henry  Marketing   67000

### `rename()`
- **Purpose**: Changes column names to more meaningful or standardized labels.
- **Key Parameter**:
    - `columns`: A dictionary mapping old column names to new names.

In [15]:
# Rename columns to more descriptive names
df_employees.rename(columns = {
    'EmployeeID':'Emp_ID',
    'Name':'Emp_Name',
    'Department': 'Dept',
    'Salary': "Annual_Salary"},
    inplace = True) # reassigns df_employees to be the renamed version, as opposed to just printing it temporarily, not rewritten

df_employees

   EmpID Emp_Name       Dept  Annual_Salary
0    101    Alice      Sales          60000
1    102      Bob      Sales          62000
2    103  Michael      Sales          61000
3    104    David  Marketing          65000
4    105    Henry  Marketing          67000

### `sort_values()`
- **Purpose**: Sorts the DataFrame by a specific column.
- **Key Parameter**:
    - `by`: Specifies the column(s) to sort by.
    - `ascending`: When set to `False` sorts the data in descending order.

In [20]:
# Sort by Annual_Salary in descending order
df_employees.sort_values(by = 'Annual_Salary',
                         ascending = False,
                         ignore_index=True,
                         inplace=True)

df_employees

   EmpID Emp_Name       Dept  Annual_Salary
0    105    Henry  Marketing          67000
1    104    David  Marketing          65000
2    102      Bob      Sales          62000
3    103  Michael      Sales          61000
4    101    Alice      Sales          60000

## Section 2: Method Chaining

### **Concept**: Combining several DataFrame operations into one continuous expression.

### **Advantages**:
- Improves readability and conciseness.
- Reduces the need for intermediate variables.

### Steps in this chain:
- **Concatenation**: Merges the two department DataFrames.
- **Renaming**: Standardizes column names.
- **Sorting**: Orders the DataFrame by annual salary in descending order.

In [27]:
import pandas as pd

# Department 1 data
df_dept1 = pd.DataFrame({
    'EmployeeID': [101, 102, 103],
    'Name': ['Alice', 'Bob', 'Michael'],
    'Department': ['Sales', 'Sales', 'Sales'],
    'Salary': [60000, 62000, 61000]
})

# Department 2 data
df_dept2 = pd.DataFrame({
    'EmployeeID': [104, 105],
    'Name': ['David', 'Henry'],
    'Department': ['Marketing', 'Marketing'],
    'Salary': [65000, 67000]
})

# Method chaining: Combine, rename, and sort in descending order of salary.
df_employees = (
    pd.concat([df_dept1,df_dept2],
              ignore_index=True)
    .rename(columns = {
        'EmployeeID':'Emp_ID',
        'Name':'Emp_Name',
        'Department':'Dept',
        'Salary':'Annual Salary'
    })
    .sort_values(by='Annual Salary',
                 ascending=False,
                 ignore_index=True)
)
df_employees

   Emp_ID Emp_Name       Dept  Annual Salary
0     105    Henry  Marketing          67000
1     104    David  Marketing          65000
2     102      Bob      Sales          62000
3     103  Michael      Sales          61000
4     101    Alice      Sales          60000

## Group Activity: Cleaning an Untidy Sales Dataset Using Method Chaining

### Method Chaining Instructions:
- Remove duplicates.
- Fill missing values with 0.
- Reshape the DataFrame from wide to long format.
- Sort the final DataFrame.

In [ ]:
import pandas as pd

df_sales = pd.DataFrame({
    'Product': [
        'Widget A', 'Widget B', 'Widget A', 'Widget C',
        'Widget B', 'Widget A', 'Widget D', 'Widget E',
        'Widget C', 'Widget D', 'Widget B', 'Widget E'
    ],
    'Region': [
        'North', 'South', 'North', 'East',
        'South', 'North', 'West', 'East',
        'Central', 'North', 'West', 'South'
    ],
    'Sales_Q1': [100, 200, 100, 150, None, 100, 180, 210, 140, 190, 205, 220],
    'Sales_Q2': [110, None, 110, 160, 210, 110, 185, 220, 150, 200, 215, 230],
    'Sales_Q3': [105, 205, 105, None, 215, 105, 175, 205, 145, 195, 210, 225],
    'Sales_Q4': [115, 215, 115, 165, 225, None, 190, 215, 155, 205, 220, 235]
})

print("Expanded df_sales DataFrame:")
print(df_sales)


# Method chaining: Clean the dataset in one pipeline.
df_cleaned = (
    df_sales
    .fillna(0)
    .melt(id_vars=['Product','Region'],
          value_vars=['Sales_Q1','Sales_Q2','Sales_Q3','Sales_Q4'],
          var_name='Quarter',
          value_name='Sales')
    .sort_values(
        by=['Product','Region','Quarter'], # we sorted by sales originally, can do whatever you want
        ignore_index=True
    )
    .drop_duplicates() # need to do this after melting because 
)

df_cleaned['Quarter'] = df_cleaned['Quarter'].str.replace('Sales_Q','')

df_cleaned

Expanded df_sales DataFrame:
     Product   Region  Sales_Q1  Sales_Q2  Sales_Q3  Sales_Q4
0   Widget A    North     100.0     110.0     105.0     115.0
1   Widget B    South     200.0       NaN     205.0     215.0
2   Widget A    North     100.0     110.0     105.0     115.0
3   Widget C     East     150.0     160.0       NaN     165.0
4   Widget B    South       NaN     210.0     215.0     225.0
5   Widget A    North     100.0     110.0     105.0       NaN
6   Widget D     West     180.0     185.0     175.0     190.0
7   Widget E     East     210.0     220.0     205.0     215.0
8   Widget C  Central     140.0     150.0     145.0     155.0
9   Widget D    North     190.0     200.0     195.0     205.0
10  Widget B     West     205.0     215.0     210.0     220.0
11  Widget E    South     220.0     230.0     225.0     235.0

     Product   Region Quarter  Sales
0   Widget A    North       1  100.0
3   Widget A    North       2  110.0
6   Widget A    North       3  105.0
9   Widget A    North       4  115.0
11  Widget A    North       4    0.0
12  Widget B    South       1  200.0
13  Widget B    South       1    0.0
14  Widget B    South       2    0.0
15  Widget B    South       2  210.0
16  Widget B    South       3  205.0
17  Widget B    South       3  215.0
18  Widget B    South       4  215.0
19  Widget B    South       4  225.0
20  Widget B     West       1  205.0
21  Widget B     West       2  215.0
22  Widget B     West       3  210.0
23  Widget B     West       4  220.0
24  Widget C  Central       1  140.0
25  Widget C  Central       2  150.0
26  Widget C  Central       3  145.0
27  Widget C  Central       4  155.0
28  Widget C     East       1  150.0
29  Widget C     East       2  160.0
30  Widget C     East       3    0.0
31  Widget C     East       4  165.0
32  Widget D    North       1  190.0
33  Widget D    North       2  200.0
34  Widget D    North       3  195.0
35  Widget D    North       4  205.0
36  Widget D     West       1  180.0
37  Widget D     West       2  185.0
38  Widget D     West       3  175.0
39  Widget D     West       4  190.0
40  Widget E     East       1  210.0
41  Widget E     East       2  220.0
42  Widget E     East       3  205.0
43  Widget E     East       4  215.0
44  Widget E    South       1  220.0
45  Widget E    South       2  230.0
46  Widget E    South       3  225.0
47  Widget E    South       4  235.0

In [49]:
import seaborn as sns
# Create a pivot table that calculates the sum of sales per Product per Region

pivot_table_sales = pd.pivot_table(
    df_cleaned,
    values = 'Sales',
    index = ['Product','Region'],
    # columns = 'Quarter',
    aggfunc = sum # sums if there are multiple values for one quarter product region
)

pivot_table_sales

/var/folders/12/d0pr40t970g0zd82449b27f40000gn/T/ipykernel_72885/1893193737.py:4: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pivot_table_sales = pd.pivot_table(

                   Sales
Product  Region
Widget A North     430.0
Widget B South    1270.0
         West      850.0
Widget C Central   590.0
         East      475.0
Widget D North     790.0
         West      730.0
Widget E East      850.0
         South     910.0